using System.Text;
using System.Text.Json;
using Visual_Block_Studio.Contracts;
using Visual_Block_Studio.DTOs;
using Visual_Block_Studio.DTOs.Explorer;
using Visual_Block_Studio.Helpers;
using Visual_Block_Studio.Models.Explorer;
using Visual_Block_Studio.Models.XamlBlocks;

namespace Visual_Block_Studio.Services;

public class VBSProjectManager(TemplateProjectService templateService)
{
    private readonly JsonSerializerOptions Options = new() { WriteIndented = true };

    public VBSProject Load(string filePath) => LoadDto(filePath).MapDtoToProj();

    public bool TryLoad(string filePath, out VBSProject proj)
    {
        try
        {
            proj = Load(filePath);
            return true;
        }
        catch (Exception)
        {
            proj = null!;
            return false;
        }
    }

    public VBSProjectDto LoadDto(string filePath)
    {
        using var fileStream = File.OpenRead(filePath);

        var dto = JsonSerializer.Deserialize<VBSProjectDto>(fileStream)
            ?? throw new InvalidOperationException("Invalid visual block file.");

        return dto;
    }

    public bool TryLoadDto(string filePath, out VBSProjectDto dto)
    {
        try
        {
            dto = LoadDto(filePath);
            return true;
        }
        catch (Exception)
        {
            dto = null!;
            return false;
        }
    }

    public bool Save(string filePath, VBSProject proj)
    {
        try
        {
            var dto = proj.MapProjToDto();

            using var fileStream = File.Create(filePath);
            JsonSerializer.Serialize(fileStream, dto, Options);

            // Keep the read-only mirrors in sync
            EmitGeneratedConstants(dto);
            MSBuildProjectGenerator.EmitCsProj(dto);

            return true;
        }
        catch (Exception)
        {
            return false;
        }
    }

    public async Task<VBSProject> CreateProjectAsync(CreateProjectRequest request)
    {
        VBSProjectDto project = await templateService.CreateWinUITemplateProjectAsync(request);

        // Write the .vbsproj JSON — this is the VBS project file.
        using var fileStream = File.Create(project.FilePath);
        JsonSerializer.Serialize(fileStream, project, Options);

        // Generate supporting files and the .NET/WinUI project file.
        EmitGeneratedConstants(project);
        MSBuildProjectGenerator.EmitCsProj(project);

        return project.MapDtoToProj();
    }

    public string EmitGeneratedConstants(VBSProjectDto dto)
    {
        var generatedDir = Path.GetDirectoryName(dto.GeneratedFilePath)
            ?? throw new InvalidOperationException($"Could not resolve directory for '{dto.GeneratedFilePath}'.");

        Directory.CreateDirectory(generatedDir);

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("//");
        sb.AppendLine($"//     This file is a READ-ONLY, human-readable mirror of '{dto.FileName}'.");
        sb.AppendLine("//     It exists purely for readability and has NO EFFECT on the project.");
        sb.AppendLine("//     It is not compiled, not referenced, and not parsed by anything.");
        sb.AppendLine("//     Editing this file does absolutely nothing — the .vbsproj JSON file");
        sb.AppendLine("//     is the only source of truth, and this file is fully overwritten");
        sb.AppendLine("//     every time the project is saved.");
        sb.AppendLine("//");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine();
        sb.AppendLine("internal static class ProjectConstants");
        sb.AppendLine("{");
        sb.AppendLine($"    public const string Name = \"{Escape(dto.Name)}\";");
        sb.AppendLine($"    public const string TargetArchitecture = \"{Escape(dto.TargetArchitecture)}\";");
        sb.AppendLine($"    public const uint MemoryLimitBytes = {dto.MemoryLimitBytes};");
        sb.AppendLine($"    public const string OutputPath = \"{Escape(dto.OutputPath)}\";");
        sb.AppendLine($"    public const string FileName = \"{Escape(dto.FileName)}\";");
        sb.AppendLine($"    public const string FilePath = \"{Escape(dto.FilePath)}\";");
        sb.AppendLine($"    public const string VcxProjFileName = \"{Escape(dto.CsProjFileName)}\";");
        sb.AppendLine($"    public const string VcxProjFilePath = \"{Escape(dto.CsProjFilePath)}\";");
        sb.AppendLine($"    public const string GeneratedFileName = \"{Escape(dto.GeneratedFileName)}\";");
        sb.AppendLine($"    public const string GeneratedFilePath = \"{Escape(dto.GeneratedFilePath)}\";");
        sb.AppendLine();
        sb.Append("    public static readonly LayoutItemInfo[] LayoutFiles = ");
        AppendLayoutFiles(dto.LayoutFiles, sb);
        sb.AppendLine(";");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("internal readonly struct LayoutItemInfo");
        sb.AppendLine("{");
        sb.AppendLine("    public LayoutItemInfo(string name, string type, LayoutFileInfo[] files)");
        sb.AppendLine("    {");
        sb.AppendLine("        Name = name;");
        sb.AppendLine("        Type = type;");
        sb.AppendLine("        Files = files;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    public string Name { get; }");
        sb.AppendLine("    public string Type { get; }");
        sb.AppendLine("    public LayoutFileInfo[] Files { get; }");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("internal readonly struct LayoutFileInfo");
        sb.AppendLine("{");
        sb.AppendLine("    public LayoutFileInfo(string fileName, string filePath, string type)");
        sb.AppendLine("    {");
        sb.AppendLine("        FileName = fileName;");
        sb.AppendLine("        FilePath = filePath;");
        sb.AppendLine("        Type = type;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    public string FileName { get; }");
        sb.AppendLine("    public string FilePath { get; }");
        sb.AppendLine("    public string Type { get; }");
        sb.AppendLine("}");

        File.WriteAllText(dto.GeneratedFilePath, sb.ToString());

        return dto.GeneratedFilePath;
    }

    private static void AppendLayoutFiles(List<ProjectItemDto> layoutFiles, StringBuilder sb)
    {
        if (layoutFiles.Count == 0)
        {
            sb.Append("[]");
            return;
        }

        sb.AppendLine("new LayoutItemInfo[]");
        sb.AppendLine("    {");
        for (int i = 0; i < layoutFiles.Count; i++)
        {
            var item = layoutFiles[i];
            sb.AppendLine($"        new(\"{Escape(item.Name)}\", \"{item.Type}\", new LayoutFileInfo[]");
            sb.AppendLine("        {");
            for (int j = 0; j < item.Files.Count; j++)
            {
                var file = item.Files[j];
                sb.Append($"            new(\"{Escape(file.FileName)}\", \"{Escape(file.FilePath)}\", \"{file.Type}\")");
                sb.AppendLine(j < item.Files.Count - 1 ? "," : "");
            }
            sb.Append("        })");
            sb.AppendLine(i < layoutFiles.Count - 1 ? "," : "");
        }
        sb.Append("    }");
    }

    private static string Escape(string value) => value.Replace("\\", "\\\\").Replace("\"", "\\\"");

    public XamlBlock LoadBlockFile(ProjectFileDto file)
    {
        using var fs = File.OpenRead(file.FilePath);

        var document = JsonSerializer.Deserialize<VBlockDocumentDto>(fs);

        if (document?.Root is null)
        {
            throw new InvalidOperationException($"Invalid block file '{file.FilePath}'.");
        }

        return (XamlBlock)document.Root.MapDtoToBlock();
    }
}